steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/frdemo2/fr-test-demo2:$SHORT_SHA',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/frdemo2/fr-test-demo2:$SHORT_SHA',
      ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'cloud-run-continuous-deployment-example',
	'--platform=managed',
        '--image=gcr.io/frdemo2/fr-test-demo2:$SHORT_SHA',
        '--region=us-central1'
      ]

